### ISSUE TITLE
Document what OS's are supported

### ISSUE THREAD

**Issue by spuder** [SteveyO/Hue-Emulator#10]
It would be nice if the readme covered the following topics:

What OS's are supported (mac, linux windows)
What version of Java is required
How to start the app

Sidenote:  It looks like there are 4 versions inside the download. Which version should be used?

**Comment by SteveyO** [comment]
Hi,

Java is platform independent, so no need to specify which OS versions are supported.  Any system which has  a JVM installed should work (works on Mac, Windows and Linux)

The emulator was compiled in 1.6 

To start the app is explained in:
http://steveyo.github.io/Hue-Emulator/
i.e. Double click the executable .jar or run from the command line.
 
The latest version is usually the best (v0.4 at time of writing).     I document the changes in each version in the CHANGELOG.md file.
