### ISSUE TITLE
Pairing issue

### ISSUE THREAD

**Issue by okachobi** [SteveyO/Hue-Emulator#11]
Its unclear whether I'm doing something wrong, but on my wired iMac I'm starting the app as root so it can listen on port 80 and neither my iOS app nor the Amazon Echo can find it after pushing the link button.  Is there another way to confirm that UPNP is working?

**Comment by SteveyO** [comment]
Am not quite sure I understand what you mean.  The push linking and UPNP are 2 different things.   UPNP finds a list of bridges. Once a bridge is found you connect to the bridge with an IP and a username (and if the username is not on the whitelist you need to  pushlink). 

I have tested the Emulator with the iOS SDK and the UPNP doesn't seem to work with this for some reason (doesn't find any bridges).   Being a Java guy myself I haven't got the resources/skills to debug why at the moment, but it is something I hope to fix one day.

I will update the documentation to make this clearer actually as I just noticed it can be improved here.

**Comment by okachobi** [comment]
When I'm referring to UPNP, I'm talking about the SSDP multicast discovery.  Is there a way to start in a debug mode so I see a log of any queries?  I have a feeling something is intercepting the port 1900 broadcasts.

**Comment by okachobi** [comment]
As it turned out, my issue appears to be related to the way my WAP bridges traffic.  It was not bridging the multicast packets.  When I moved the Echo to a room with a different model WAP it worked.  Thanks!
