### ISSUE TITLE
Running emulator on OSX

### ISSUE THREAD

**Issue by komis1** [SteveyO/Hue-Emulator#12]
Not really an issue - emulator works fine! However, you may want to add this info on your website or Readme (as it took me a while to figure it out).

On OSX, the emulator runs without a hitch if you try to use the default port (i.e. 8000) but won't start if you set the port to 80 (required for bridging to Android). Turns out that on OSX you cannot run a server on a port <1000 unless you have root privileges. Hence when trying to run the emulator on port 80, it appears not to start (and in the terminal, you can see stacktraces from the relevant exceptions being raised).

To solve this problem, simply run "sudo java -jar HueEmulator-v0.x.jar"

**Comment by SteveyO** [comment]
Thanks for that Komis1,   I haven't tested it that thoroughly on OS X, so this is good to know.  I have updated the documentation on the website so hopefully this will be clearer for others.
