### ISSUE TITLE
Question about scenes

### ISSUE THREAD

**Issue by androidrivne** [SteveyO/Hue-Emulator#3]
Hi, does this emulator support Scenes API http://www.developers.meethue.com/documentation/java-sdk-getting-started#usingScenes ?

**Comment by SteveyO** [comment]
Hi,  

A few months ago I implemented get/create scene + scene recall.  I ran some quick tests and it seemed to work, but it hasn't been through any extensive testing + I haven't tested it with the above Java code. I can't remember implementing the 'Modify Scene' so this won't work.

Also, you need to bear in mind that the scenes are not persisted.  i.e. If you create a scene, and then restart the Emulator they will be lost.  This isn't something I plan to do in the future.

If you do use the emulator for scenes, and find anything then let me know.

Thanks
Steve

**Comment by androidrivne** [comment]
Thanks for fast reply. Can you please send that old version of emulator with working scenes, because I get "com.philips.lighting.hue.sdk.exception.PHHueInvalidAPIException: Invalid API call for Portal" when trying to save scene ?
