### ISSUE TITLE
Transition Time

### ISSUE THREAD

**Issue by milhouse34521** [SteveyO/Hue-Emulator#4]
Does setting transitiontime work in the emulator?  A simple program like this doesn't seem to work in the emulator but does with my lights.  In the emulator, I just get an immediate change while its done over the transition time with my lights.
	
lights[1].on = True
lights[1].xy = [.322,.545]
lights[1].brightness = 20
lights[1].transitiontime = 2000
time.sleep(4)
lights[1].transitiontime = 500
lights[1].brightness = 255
lights[1].xy = [.622,.145]

**Comment by milhouse34521** [comment]
And....I just saw that this is not implemented yet...Nevermind.

**Comment by SteveyO** [comment]
Actually, I was thinking recently it would be nice for the emulator to have transition times. At some point soon I will check my code and see if I can work out an easy way to do this. If I can do it without a major refactor I will see about including them.

**Comment by bipinvaylu** [comment]
Hey @SteveyO does Hue Emulator support `transitiontime` effect when setting up light state. For example: `{"sat":224,"bri":134,"hue":64374, "transitiontime": 5000}`

I am passing above payload in PUT state api call. But i am unable to find soft transition instead its do instant transition for color. I hope i am not doing anything wrong here. Thanks.
