### ISSUE TITLE
Routing to Wink Hub

### ISSUE THREAD

**Issue by anixon** [SteveyO/Hue-Emulator#6]
Hi Steve. I'm a bit of a novice here. I would like to use the emulator to take commands from my logitech harmony remote and then convert the commands to WINK api to control my lights (harmony supports HUE but not Wink out of the box right now). Would your emulator be suitable for this task?

Thanks!

**Comment by SteveyO** [comment]
Hi there,
I haven't played with the logitech harmony remote or the WINK api either so I can't say for sure.

The emulator was created mainly for developing applications, but it should work with some 3rd party applications that use the hue system albeit with some limitations. Bear in mind you will have to run it on port 80 for this (in case the app is using UPNP to find the hue bridge).  Also bear in mind the Emulator doesn't have rules, sensors and some other effects (transition, alerts) so any app that uses them will not function well on the emulator also.

In any case the Emulator is a runnable jar file (Hue-Emulator-v03.jar in main root github project), so it should be relatively easy to test if it works with any other app or technology.  Let me know if it works.
Hope this helps.
Steve
